name: Auto-update hockey scores

on:
  schedule:
    - cron: '*/5 10-23 * 5 *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch & update scores
        run: curl -s "https://fantasy-hokej-2026.vercel.app/api/update" || true
